### ISSUE TITLE
Can you add a trade/stop call to the example.py code so I know how to use it?

### ISSUE THREAD

**Issue by scumola** [Panzki/sparkprofit-api#1]
Just wondering if you could add a trade and stop call to the example code so I know how to use those calls.

**Comment by scumola** [comment]
and maybe something that shows the open trades?

**Comment by Panzki** [comment]
Sure, I'll add this later this weekend. Please let me know if you have other suggestions or found any bugs.

Greetings
Panzki

**Comment by Panzki** [comment]
@scumola check out the tradeExample.py

While working on this I noticed, that sparkprofit changed their api so I'm not sure if everything works as expected. If you encounter any problems, please let me know.
